deploymentName: user-management-deployment
deploymentLabel: user-management

replicaCount: 1

image:
  repository: leonarda123/user-management-service
  tag: latest

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

kafka_enabled: true
eureka_enabled: true
zipkin_enabled: false
mailing_enabled: false
mongo_user_management_enabled: true
mongo_post_enabled: false
neo4j_enabled: false
postgresql_appointments_enabled: false
postgresql_feed_enabled: false