apiVersion: v2
name: dev-environment
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: hsma-common
    version: 0.1.0
    repository: file://../hsma-common

  - name: eureka-server
    version: 0.1.0
    repository: file://../hsma-services/eureka-server

  - name: appointment-service
    version: 0.1.0
    repository: file://../hsma-services/appointment-service

  - name: mail-service
    version: 0.1.0
    repository: file://../hsma-services/mail-service

  - name: post-feed-service
    version: 0.1.0
    repository: file://../hsma-services/post-feed-service

  - name: post-service
    version: 0.1.0
    repository: file://../hsma-services/post-service

  - name: relationship-service
    version: 0.1.0
    repository: file://../hsma-services/relationship-service

  - name: user-management-service
    version: 0.1.0
    repository: file://../hsma-services/user-management-service

  - name: api-gateway-service
    version: 0.1.0
    repository: file://../hsma-services/api-gateway-service