rule_files:
  - "prometheus_rules.yaml"

scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          application: 'Gateway Service'