{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
      - name: {{ .Values.deploymentLabel }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
        {{- if .Values.kafka_enabled }}
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
        {{- end }}
        {{- if .Values.eureka_enabled }}
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        {{- end }}
        {{- if .Values.zipkin_enabled }}
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
        {{- end }}
        {{- if .Values.mailing_enabled }}
        - name: URLVALIDATION
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MAIL_URL_VALIDATION
        - name: URLACCEPTAPPOINTMENT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MAIL_ACCEPT_APPOINTMENT
        - name: URLREFUSEAPPOINTMENT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MAIL_REFUSE_APPOINTMENT
        {{- end }}
        {{- if .Values.mongo_user_management_enabled }}
        - name: SPRING_DATA_MONGODB_URI
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: MONGO_CONNECTION_USER_MANAGEMENT
        {{- end }}
        {{- if .Values.mongo_post_enabled }}
        - name: SPRING_DATA_MONGODB_URI
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: MONGO_CONNECTION_POST
        {{- end }}
        {{- if .Values.neo4j_enabled }}
        - name: SPRING_DATA_NEO4J_URI
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: NEO4J_CONNECTION_URI
        - name: SPRING_DATA_NEO4J_AUTHENTICATION_USERNAME
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: NEO4J_USERNAME
        - name: SPRING_DATA_NEO4J_AUTHENTICATION_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: NEO4J_PASSWORD
        {{- end }}
        {{- if .Values.postgresql_appointments_enabled }}
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: POSTGRESQL_CONNECTION_APPOINTMENTS
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: POSTGRESQL_USERNAME_ROOT
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: POSTGRESQL_PASSWORD_ROOT
        {{- end }}
        {{- if .Values.postgresql_feed_enabled }}
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: POSTGRESQL_CONNECTION_FEED
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: POSTGRESQL_USERNAME_ROOT
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.global.secretConfigName }}
              key: POSTGRESQL_PASSWORD_ROOT
        {{- end }}
{{- end -}}