spring:
  application:
    name: appointment-service

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/appointments
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          appointmentConsumer-in-0:
            consumer:
              startOffset: earliest
      bindings:
        appointmentConsumer-in-0:
          destination: userChannel
          contentType: application/json
          group: appointmentService
        appointmentChannel-out-0:
          destination: appointmentChannel
          contentType: application/json

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
