apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    app: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: leonarda123/user-management-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: user-management-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  selector:
    app: user-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
