spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: relationship-service
          uri: lb://relationship-service
          predicates:
            - Path=/relationship/**
          filters:
            - AuthenticationFilter
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**
          filters:
            - AuthenticationFilter
        - id: post-feed-service
          uri: lb://post-feed-service
          predicates:
            - Path=/feed/**
          filters:
            - AuthenticationFilter
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointment/**
          filters:
            - AuthenticationFilter

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true


